# Generated by Django 3.0.3 on 2020-03-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EffectCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PriceBubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaule', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatBubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaule', models.IntegerField(default=0)),
                ('next', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_bubble', to='Gameobjcets.PriceBubble')),
                ('prev', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_bubble', to='Gameobjcets.PriceBubble')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValuesOnLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl1', models.IntegerField(default=-1)),
                ('lvl2', models.IntegerField(default=-1)),
                ('lvl3', models.IntegerField(default=-1)),
                ('lvl4', models.IntegerField(default=-1)),
                ('lvl5', models.IntegerField(default=-1)),
                ('dop', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ManyToManyField(to='Gameobjcets.EffectCollector')),
                ('live', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armor_stats', to='Gameobjcets.StatBubble')),
                ('attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_stats', to='Gameobjcets.StatBubble')),
                ('magic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magic_stats', to='Gameobjcets.StatBubble')),
                ('range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_stats', to='Gameobjcets.StatBubble')),
                ('speed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speed_stats', to='Gameobjcets.StatBubble')),
            ],
        ),
        migrations.CreateModel(
            name='Slowdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ManyToManyField(to='Gameobjcets.EffectCollector')),
                ('live', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slowdown_effect', to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('cooldown', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
            ],
        ),
        migrations.CreateModel(
            name='Silence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ManyToManyField(to='Gameobjcets.EffectCollector')),
                ('live', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ManyToManyField(to='Gameobjcets.EffectCollector')),
                ('live', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shield_effect', to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poisoning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ManyToManyField(to='Gameobjcets.EffectCollector')),
                ('live', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poisoning_effect', to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('e', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_e', to='Gameobjcets.Skill')),
                ('q', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_q', to='Gameobjcets.Skill')),
                ('r', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_r', to='Gameobjcets.Skill')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.Stats')),
                ('w', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_w', to='Gameobjcets.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.Stats')),
            ],
        ),
        migrations.CreateModel(
            name='Heal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ManyToManyField(to='Gameobjcets.EffectCollector')),
                ('live', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heal_effect', to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ManyToManyField(to='Gameobjcets.EffectCollector')),
                ('live', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsToTargetSubSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.Damage')),
                ('effects', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.EffectCollector')),
                ('range', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsInZoneSubSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.Damage')),
                ('effects', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.EffectCollector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsInRadiusSubSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.Damage')),
                ('effects', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.EffectCollector')),
                ('range', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='damage',
            name='clear',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clear', to='Gameobjcets.ValuesOnLevels'),
        ),
        migrations.AddField(
            model_name='damage',
            name='magical',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magical', to='Gameobjcets.ValuesOnLevels'),
        ),
        migrations.AddField(
            model_name='damage',
            name='physical',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical', to='Gameobjcets.ValuesOnLevels'),
        ),
        migrations.CreateModel(
            name='Bleeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ManyToManyField(to='Gameobjcets.EffectCollector')),
                ('live', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttackBuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ManyToManyField(to='Gameobjcets.EffectCollector')),
                ('live', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attack_buf_effect', to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
