# Generated by Django 3.0.3 on 2020-03-16 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armor_stat', to='Gameobjcets.StatBubble'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack_stat', to='Gameobjcets.StatBubble'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='magic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magic_stat', to='Gameobjcets.StatBubble'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_stat', to='Gameobjcets.StatBubble'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='speed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speed_stat', to='Gameobjcets.StatBubble'),
        ),
    ]
