# Generated by Django 3.0.3 on 2020-03-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hero',
            name='proto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.HeroPrototype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heroprototype',
            name='hp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gameobjcets.ValuesOnLevels'),
        ),
    ]
