# Generated by Django 3.0.3 on 2020-03-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0002_auto_20200309_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackbuf',
            name='effects',
            field=models.ManyToManyField(related_name='attackbuf_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AddField(
            model_name='bleeding',
            name='effects',
            field=models.ManyToManyField(related_name='bleeding_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AddField(
            model_name='fetter',
            name='effects',
            field=models.ManyToManyField(related_name='fetter_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AddField(
            model_name='heal',
            name='effects',
            field=models.ManyToManyField(related_name='heal_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AddField(
            model_name='hero',
            name='effects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero', to='Gameobjcets.Effect'),
        ),
        migrations.AddField(
            model_name='poisoning',
            name='effects',
            field=models.ManyToManyField(related_name='poisoning_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AddField(
            model_name='shield',
            name='effects',
            field=models.ManyToManyField(related_name='shield_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AddField(
            model_name='silence',
            name='effects',
            field=models.ManyToManyField(related_name='silence_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AddField(
            model_name='slowdown',
            name='effects',
            field=models.ManyToManyField(related_name='slowdown_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AddField(
            model_name='stun',
            name='effects',
            field=models.ManyToManyField(related_name='stun_proto', to='Gameobjcets.Effect'),
        ),
    ]
