# Generated by Django 3.0.3 on 2020-03-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0002_auto_20200316_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsCooldowns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_cooldown', models.IntegerField(default=0)),
                ('w_cooldown', models.IntegerField(default=0)),
                ('e_cooldown', models.IntegerField(default=0)),
                ('r_cooldown', models.IntegerField(default=0)),
                ('e', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_MY', to='Gameobjcets.Skill')),
                ('q', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_MY', to='Gameobjcets.Skill')),
                ('r', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_MY', to='Gameobjcets.Skill')),
                ('w', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='w_MY', to='Gameobjcets.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gameobjcets.SkillsCooldowns'),
        ),
    ]
