# Generated by Django 3.0.3 on 2020-03-17 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0002_auto_20200317_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillscooldowns',
            name='e',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_MY', to='Gameobjcets.Skill'),
        ),
        migrations.AlterField(
            model_name='skillscooldowns',
            name='q',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_MY', to='Gameobjcets.Skill'),
        ),
        migrations.AlterField(
            model_name='skillscooldowns',
            name='r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_MY', to='Gameobjcets.Skill'),
        ),
        migrations.AlterField(
            model_name='skillscooldowns',
            name='w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='w_MY', to='Gameobjcets.Skill'),
        ),
    ]
