# Generated by Django 3.0.3 on 2020-03-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0003_auto_20200310_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackbuf',
            name='collector',
            field=models.ManyToManyField(blank=True, null=True, to='Gameobjcets.EffectCollector'),
        ),
        migrations.AlterField(
            model_name='bleeding',
            name='collector',
            field=models.ManyToManyField(blank=True, null=True, to='Gameobjcets.EffectCollector'),
        ),
        migrations.AlterField(
            model_name='fetter',
            name='collector',
            field=models.ManyToManyField(blank=True, null=True, to='Gameobjcets.EffectCollector'),
        ),
        migrations.AlterField(
            model_name='heal',
            name='collector',
            field=models.ManyToManyField(blank=True, null=True, to='Gameobjcets.EffectCollector'),
        ),
        migrations.AlterField(
            model_name='poisoning',
            name='collector',
            field=models.ManyToManyField(blank=True, null=True, to='Gameobjcets.EffectCollector'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='collector',
            field=models.ManyToManyField(blank=True, null=True, to='Gameobjcets.EffectCollector'),
        ),
        migrations.AlterField(
            model_name='silence',
            name='collector',
            field=models.ManyToManyField(blank=True, null=True, to='Gameobjcets.EffectCollector'),
        ),
        migrations.AlterField(
            model_name='slowdown',
            name='collector',
            field=models.ManyToManyField(blank=True, null=True, to='Gameobjcets.EffectCollector'),
        ),
        migrations.AlterField(
            model_name='stun',
            name='collector',
            field=models.ManyToManyField(blank=True, null=True, to='Gameobjcets.EffectCollector'),
        ),
    ]
