# Generated by Django 3.0.3 on 2020-03-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0003_auto_20200317_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackbuf',
            name='value',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attackbuf_effect', to='Gameobjcets.ValuesOnLevels'),
        ),
        migrations.CreateModel(
            name='SpeedUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ManyToManyField(blank=True, related_name='speedup_effects_set', to='Gameobjcets.EffectCollector')),
                ('effects', models.ManyToManyField(blank=True, related_name='speedup_proto', to='Gameobjcets.Effect')),
                ('live', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gameobjcets.ValuesOnLevels')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speedup_effect', to='Gameobjcets.ValuesOnLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
