# Generated by Django 3.0.3 on 2020-03-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0004_auto_20200310_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='effects',
        ),
        migrations.AddField(
            model_name='hero',
            name='effects',
            field=models.ManyToManyField(blank=True, null=True, related_name='hero', to='Gameobjcets.Effect'),
        ),
    ]
