# Generated by Django 3.0.3 on 2020-03-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0004_auto_20200317_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectsinradiussubskill',
            name='skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='effectsinradiussubskill_subskills_MY', to='Gameobjcets.Skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='effectsinzonesubskill',
            name='skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='effectsinzonesubskill_subskills_MY', to='Gameobjcets.Skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='effectstotargetsubskill',
            name='skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='effectstotargetsubskill_subskills_MY', to='Gameobjcets.Skill'),
            preserve_default=False,
        ),
    ]
