# Generated by Django 3.0.3 on 2020-03-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0005_auto_20200310_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='shield',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attackbuf',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='attackbuf_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AlterField(
            model_name='bleeding',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='bleeding_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AlterField(
            model_name='fetter',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='fetter_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AlterField(
            model_name='heal',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='heal_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='effects',
            field=models.ManyToManyField(blank=True, null=True, to='Gameobjcets.Effect'),
        ),
        migrations.AlterField(
            model_name='poisoning',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='poisoning_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='shield_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AlterField(
            model_name='silence',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='silence_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AlterField(
            model_name='slowdown',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='slowdown_proto', to='Gameobjcets.Effect'),
        ),
        migrations.AlterField(
            model_name='stun',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='stun_proto', to='Gameobjcets.Effect'),
        ),
    ]
