# Generated by Django 3.0.3 on 2020-03-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0006_auto_20200311_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='shield',
        ),
    ]
