# Generated by Django 3.0.3 on 2020-03-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gameobjcets', '0008_auto_20200311_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='my_effects',
            field=models.ManyToManyField(blank=True, related_name='maker_set', to='Gameobjcets.Effect'),
        ),
    ]
